Jdp210602 14 cart
adrianpaz/project_06_2012 pull request #14
Opened 2021-06-27 13:04 UTC by D4nielZ4k

Robiłem trochę po omacku czekam na jakieś opinie.

2021-06-27 15:00 UTC, jakjur-dev approved these changes

2021-06-29 18:16 UTC, adrianpaz requested changes
Update entity

2021-07-01 15:49 UTC, adrianpaz commented
Build nie przechodzi na branchu

2021-07-01 16:17 UTC, D4nielZ4k commented on build.gradle
> -    runtimeOnly 'mysql:mysql-connector-java'
Nie ruszałem tego. W jakim to commicie?

2021-07-02 11:38 UTC, closed without merging