Jdp210602 16 Encja Order - testy
adrianpaz/project_06_2012 pull request #27
Opened 2021-07-04 22:04 UTC by ga1robe

Encja Order - testy

2021-07-05 17:37 UTC, jakjur-dev commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> -    private User user;
Wydaje mi się, że mógł zostać User, w kolumnie powinno i tak pojawić się ID użytkownika

2021-07-05 17:37 UTC, jakjur-dev commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -    private String groupId;
Tutaj podobnie

2021-07-05 18:22 UTC, adrianpaz requested changes

2021-07-05 18:22 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +public class UserController {
Tych zmian nie powinno być w tym PR.

2021-07-05 18:29 UTC, ga1robe commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +public class UserController {
Nie rozumiem, przecież ja tutaj nic nie zmieniałem.

2021-07-05 19:37 UTC, ga1robe commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> -    private User user;
Nie może zostać User. Skończyłoby się to błędem niedopasowanych wartości.

Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)....

2021-07-05 19:49 UTC, ga1robe commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -    private String groupId;
Mogły to być zmiany przesunięcia linii, na przykład po dopisaniu/usunięciu linii z grupy import.

2021-07-06 17:16 UTC, adrianpaz approved these changes

2021-07-06 17:19 UTC, merged