OrderController zwracanie danych testowych
adrianpaz/project_06_2012 pull request #4
Opened 2021-06-25 17:35 UTC by ga1robe

Zgodnie z opisem przygotowanie "pustego" kontrolera REST, dodanie implementacji endpointów, zwracającnie sztucznych danych.

2021-06-27 16:53 UTC, jakjur-dev approved these changes

2021-06-27 16:56 UTC, jakjur-dev reviewed
Niektóre testy jeszcze nie przechodzą

2021-06-27 18:29 UTC, D4nielZ4k approved these changes

2021-06-27 19:33 UTC, ga1robe commented
Poprawiłem w build.gradle. Nie wiem czemu się wyświetla.

W src/main/resources/application.properties nie poprawię.

To na master jest błąd. Powtórzony dwa razy jeden parametr.

2021-06-28 07:14 UTC, MARudnicki requested changes

2021-06-28 07:14 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/CardDto.java
> +    List<ProductDto> shoppingCart = new ArrayList<>();
zmienne powinny byc private

2021-06-28 07:14 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/OrderDto.java
> +    List<ProductDto> OrderProducts = new ArrayList<>();
analogicznie jak wyzej - zmienne powinny byc private

2021-06-28 07:14 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/OrderDto.java
> +    List<ProductDto> OrderProducts = new ArrayList<>();
dlaczego OrderProducts?
- nazwa zmiennej powinna byc od malej litery
- wystarczy nazwa products

2021-06-28 07:14 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/UserDto.java
> +    public List<OrderDto> getUser() { return new ArrayList<>(); }
skad ta metoda? Dlaczego 'getUser' zwraca liste OrderDto ?

2021-06-28 07:57 UTC, ga1robe commented
Poprawiłem. Pewnie trzeba będzie czekać wieki na ponowne review.

2021-06-28 15:32 UTC, ga1robe reviewed
Dawno poprwione na prywane

2021-06-28 18:28 UTC, MARudnicki requested changes

2021-06-28 18:28 UTC, MARudnicki commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
linie 
```
compileOnly 'org.projectlombok:lombok'
annotationProcessor 'org.projectlombok:lombok'
```
sa zdublowane

2021-06-28 18:28 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/CardDto.java
> +    private UserDto user;
Oba CardDto oraz OrderDto zawieraja relacje do usera. Tutaj wystarczy userId jak w OrderDto

2021-06-28 18:28 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/OrderDto.java
> +    private long idUser;
idUser -> userId

2021-06-28 18:37 UTC, ga1robe commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
Linie te nie są zdublowane.

Tak było w `master`.

Czy coś się zmieniło...

2021-06-28 18:50 UTC, ga1robe commented on src/main/java/com/kodilla/dto/OrderDto.java
> +    private long idUser;
Poprawiłem.

2021-06-28 19:03 UTC, ga1robe commented on src/main/java/com/kodilla/dto/CardDto.java
> +    private UserDto user;
Poprawiłem.

2021-06-30 07:31 UTC, merged