Jdp210602 3 cart controller
adrianpaz/project_06_2012 pull request #6
Opened 2021-06-25 18:15 UTC by D4nielZ4k

2021-06-25 20:14 UTC, andrzej-t commented
W CartController (tym zwracającym testowe dane) w 39 linijce jest literówka "crateOrder" zamiast "createOrder"... Resztę na razie próbuję ogarnąć, więc na razie się nie wypowiadam.

2021-06-26 19:14 UTC, D4nielZ4k commented
Poprawione.

2021-06-27 14:01 UTC, ga1robe approved these changes

2021-06-27 15:06 UTC, jakjur-dev approved these changes

2021-06-28 07:18 UTC, MARudnicki requested changes

2021-06-28 07:18 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/CartDto.java
> +    List<ProductDto> shoppingCart = new ArrayList<>();
zmienne powinny byc private

2021-06-28 07:18 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/OrderDto.java
> +    List<ProductDto> OrderProducts = new ArrayList<>();
zmienne powinny byc private. Nazwa OrderProducts -> products/productDtos

2021-06-28 07:18 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/ProductDto.java
> +    String groupId;
zmienne powinny byc private

2021-06-28 07:18 UTC, MARudnicki commented on src/main/java/com/kodilla/dto/UserDto.java
> +    BigDecimal userKey;
private ..

2021-06-28 07:18 UTC, MARudnicki commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/kodilla_project?serverTimezone=Europe/Warsaw&useSSL=False&useSSL=False&allowPublicKeyRetrieval=true
flaga useSSL=False jest zduplikowana

2021-06-28 07:18 UTC, MARudnicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +        return cartDto.getShoppingCart();
ta metoda powinna albo:
- byc void
- albo zwracac id Ordera
- albo zwracac OrderDto

Na pewno nie powinna zwracac ProductDto

2021-06-28 18:30 UTC, MARudnicki requested changes

2021-06-28 18:30 UTC, MARudnicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +        new CartDto(userDto, new ArrayList<>());
z tym CardDto nic sie nie dzieje - nie jest zapisywane, ani przekazywane dalej. Jest do usuniecia

2021-06-28 18:30 UTC, MARudnicki commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok:1.18.20'
wersja lomboka jest zbedna - zostanie odziedziczona z pluginu springboota

2021-06-30 20:31 UTC, jakjur-dev approved these changes

2021-07-01 16:06 UTC, merged